
# Site settings
title: Tim Elam Resume 
description: Atlanta Software Guy Tim Elam's Resume
favicon: /assets/img/avatar.JPG
url: https://tim-elam.dev
rss_url: /pages/atom.xml
google_analytics: UA-38748317-2
# Build settings
markdown: kramdown

include: [".well-known"]
exclude: [vendor]