
# Site settings
title: Tim Elam's Resume
description: Atlanta Software Guy Tim Elam's Resume
favicon: /assets/img/avatar.JPG
url: https://tim-elam.dev
rss_url: /pages/atom.xml
# Build settings
markdown: kramdown

include: [".well-known"]
exclude: [vendor]
